src/Entity/Basket.php
<?php

namespace App\Entity;

use App\Repository\BasketRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=BasketRepository::class)
 */
class Basket
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $creation_date;

    /**
     * @ORM\Column(type="date")
     */
    private $pickup_date;

    /**
     * @ORM\Column(type="integer")
     */
    private $stock;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\OneToMany(targetEntity=Order::class, mappedBy="basket")
     */
    private $orders;

    public function __construct()
    {
        $this->orders = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCreationDate(): ?\DateTimeInterface
    {
        return $this->creation_date;
    }

    public function setCreationDate(\DateTimeInterface $creation_date): self
    {
        $this->creation_date = $creation_date;

        return $this;
    }

    public function getPickupDate(): ?\DateTimeInterface
    {
        return $this->pickup_date;
    }

    public function setPickupDate(\DateTimeInterface $pickup_date): self
    {
        $this->pickup_date = $pickup_date;

        return $this;
    }

    public function getStock(): ?int
    {
        return $this->stock;
    }

    public function setStock(int $stock): self
    {
        $this->stock = $stock;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return Collection|Order[]
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    public function addOrder(Order $order): self
    {
        if (!$this->orders->contains($order)) {
            $this->orders[] = $order;
            $order->setBasket($this);
        }

        return $this;
    }

    public function removeOrder(Order $order): self
    {
        if ($this->orders->removeElement($order)) {
            // set the owning side to null (unless already changed)
            if ($order->getBasket() === $this) {
                $order->setBasket(null);
            }
        }

        return $this;
    }
}

src/Entity/Order.php
<?php

namespace App\Entity;

use App\Repository\OrderRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=OrderRepository::class)
 * @ORM\Table(name="`order`")
 */
class Order
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string")
     */
    private $order_date;

    /**
     * @ORM\Column(type="integer")
     */
    private $quantity;

    /**
     * @ORM\ManyToOne(targetEntity=Basket::class, inversedBy="orders")
     * @ORM\JoinColumn(nullable=false)
     */
    private $basket;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="orders")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getOrderDate(): ?string
    {
        return $this->order_date;
    }

    public function setOrderDate(string $order_date): self
    {
        $this->order_date = $order_date;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getBasket(): ?Basket
    {
        return $this->basket;
    }

    public function setBasket(?Basket $basket): self
    {
        $this->basket = $basket;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Form/BasketType.php
<?php

namespace App\Form;

use App\Entity\Basket;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BasketType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('creation_date')
            ->add('pickup_date')
            ->add('stock')
            ->add('description')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Basket::class,
        ]);
    }
}

src/Controller/BasketController.php
<?php

namespace App\Controller;

use App\Entity\Order;
use App\Entity\Basket;
use App\Form\BasketType;
use App\Repository\OrderRepository;
use App\Repository\BasketRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @Route("/basket")
 */
class BasketController extends AbstractController
{
    /**
     * @Route("/", name="basket_index", methods={"GET"})
     */
    public function index(BasketRepository $basketRepository): Response
    {
        return $this->render('basket/index.html.twig', [
            'baskets' => $basketRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="basket_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $basket = new Basket();
        $form = $this->createForm(BasketType::class, $basket);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($basket);
            $entityManager->flush();

            return $this->redirectToRoute('basket_index');
        }

        return $this->render('basket/new.html.twig', [
            'basket' => $basket,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="basket_show", methods={"GET"})
     */
    public function show(Basket $basket, $id, OrderRepository $orderRepository): Response
    {
        $orders = $orderRepository->findBy(['basket' => $id]);

        return $this->render('basket/show.html.twig', [
            'basket' => $basket,
            'orders' => $orders,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="basket_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Basket $basket): Response
    {
        $form = $this->createForm(BasketType::class, $basket);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('basket_index');
        }

        return $this->render('basket/edit.html.twig', [
            'basket' => $basket,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="basket_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Basket $basket): Response
    {
        if ($this->isCsrfTokenValid('delete'.$basket->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($basket);
            $entityManager->flush();
        }

        return $this->redirectToRoute('basket_index');
    }


    /**
     * @Route("/post/basket/reserve/{id}", name="basket_reserve")
     */
    public function reserved($id, BasketRepository $basketRepository)
    {
        $time = new \DateTime();


        $order = new Order();

        $user = $this->getUser();
        $basket = $basketRepository->find($id);

        $order->setQuantity('1');
        $order->setUser($user);
        $order->setBasket($basket);
        $order->setOrderDate($time -> format('Y-m-d H:i'));
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->persist($order);
        $entityManager->flush();

        return $this->redirectToRoute('basket_index');
    }
}

templates/basket/_delete_form.html.twig
<form method="post" action="{{ path('basket_delete', {'id': basket.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ basket.id) }}">
    <button class="btn">Supprimer le panier</button>
</form>

templates/basket/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}

templates/basket/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier un panier{% endblock %}

{% block body %}
    <h1>Modifier un panier</h1>

    {{ include('basket/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('basket_index') }}">Revenir à la liste</a>

    {{ include('basket/_delete_form.html.twig') }}
{% endblock %}

templates/basket/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Basket index{% endblock %}

{% block body %}
    <h1>Basket index</h1>

    <table class="table">
        <thead>
            <tr>
                {# <th>Id</th>
                <th>Creation_date</th> #}
                <th>Date de distribution</th>
                <th>Stock</th>
                {# <th>Description</th> #}
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for basket in baskets %}
            <tr>
                {# <td>{{ basket.id }}</td>
                <td>{{ basket.creationDate ? basket.creationDate|date('Y-m-d H:i:s') : '' }}</td> #}
                <td>{{ basket.pickupDate ? basket.pickupDate|date('Y-m-d') : '' }}</td>
                <td>{{ basket.stock }}</td>
                {# <td>{{ basket.description }}</td> #}
                <td>
                    <a href="{{ path('basket_show', {'id': basket.id}) }}">Détail du panier</a>
                    {# <a href="{{ path('basket_edit', {'id': basket.id}) }}">edit</a> #}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('basket_new') }}">Créer un nouveau panier</a>
{% endblock %}

templates/basket/lastBasket.html.twig
{% extends 'base.html.twig' %}

{% block title %}Basket{% endblock %}

{% block body %}
{{ basket.stock }}
{{ basket.description }}

{% if app.user %}
        <a class="button" href="{{ path('basket_reserve', {'id': basket.id}) }}">Réserver</a>
{% endif %}
{% endblock %}

templates/basket/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouveau panier{% endblock %}

{% block body %}
    <h1>Créer un nouveau panier</h1>

    {{ include('basket/_form.html.twig') }}

    <a href="{{ path('basket_index') }}">Revenir à la liste</a>
{% endblock %}

templates/basket/ordersByBasket.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commandes{% endblock %}

{% block body %}
    <h1>Commandes du dernier panier</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Prénom</th>
                <th>Nom</th>
                <th>Email</th>
                <th>Nombre de paniers</th>
                <th>Date de la réservation</th>
            </tr>
        </thead>
        <tbody>
        {% for order in orders %}
            <tr>
                <td>{{ order.user.firstname }}</td>
                <td>{{ order.user.secondname }}</td>
                <td>{{ order.user.email }}</td>
                <td>{{ order.quantity }}</td>
                <td>{{ order.orderDate }}</td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/basket/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Basket{% endblock %}

{% block body %}
    <h1>Basket</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Identifiant</th>
                <td>{{ basket.id }}</td>
            </tr>
            <tr>
                <th>Date de création</th>
                <td>{{ basket.creationDate ? basket.creationDate|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Date de collecte</th>
                <td>{{ basket.pickupDate ? basket.pickupDate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Stock</th>
                <td>{{ basket.stock }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ basket.description }}</td>
            </tr>
        </tbody>
    </table>

    {# <a href="{{ path('orders_by_basket', {'id': basket.id}) }}">commandes</a> #}

    <a href="{{ path('basket_index') }}">Revenir à la liste des paniers</a>

    {# <a href="{{ path('basket_edit', {'id': basket.id}) }}">edit</a> #}

    {{ include('basket/_delete_form.html.twig') }}
    <hr>

    <h1>Commandes du dernier panier</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Prénom</th>
                <th>Nom</th>
                <th>Email</th>
                <th>Nombre de paniers</th>
                <th>Date de la réservation</th>
            </tr>
        </thead>
        <tbody>
        {% for order in orders %}
            <tr>
                <td>{{ order.user.firstname }}</td>
                <td>{{ order.user.secondname }}</td>
                <td>{{ order.user.email }}</td>
                <td>{{ order.quantity }}</td>
                <td>{{ order.orderDate }}</td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    
{% endblock %}